import '../models/media_item.dart';
import '../models/media_type.dart';
import '../models/library_entry.dart';
import '../models/play_session.dart';

class SampleData {
  static final List<MediaItem> sampleGames = [
    const MediaItem(
      id: 'game_zelda_la',
      title: "The Legend of Zelda: Link's Awakening",
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1qve.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/sckj7b.webp',
      releaseYear: 2019,
      releaseDateFormatted: 'Sep 20, 2019',
      genres: ['Action', 'Adventure', 'Puzzle'],
      synopsis: "As Link, you awaken in a strange land away from Hyrule, where animals talk and monsters roam. To uncover the truth behind your whereabouts and awaken the legendary Wind Fish, explore Koholint Island and all its trap-ridden dungeons.",
      communityRating: 8.7,
      creator: 'Nintendo',
      runtimeMinutes: 840,
    ),
    const MediaItem(
      id: 'game_silent_hill_f',
      title: 'Silent Hill f',
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5p1d.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/scfkcw.webp',
      releaseYear: 2025,
      releaseDateFormatted: 'Sep 25, 2025',
      genres: ['Horror', 'Puzzle', 'Survival'],
      synopsis: 'Silent Hill f is an upcoming psychological survival horror video game. Set in 1960s Japan featuring a beautiful, yet terrifying world, written by Ryukishi07.',
      communityRating: 9.1,
      creator: 'Konami / NeoBards',
      runtimeMinutes: 720,
    ),
    const MediaItem(
      id: 'game_fable',
      title: 'Fable',
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5o3b.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc8c9u.webp',
      releaseYear: 2026,
      releaseDateFormatted: 'Late 2026',
      genres: ['Action', 'RPG', 'Open World'],
      synopsis: 'Become the Hero you want to be in an immersive open-world action-RPG where each choice shapes your journey, reputation is everything, and fairytale wonder meets dry British wit.',
      communityRating: 8.9,
      creator: 'Playground Games / Xbox',
      runtimeMinutes: 1800,
    ),
    const MediaItem(
      id: 'game_ac_shadows',
      title: "Assassin's Creed Shadows",
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co87o0.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/scnvb2.webp',
      releaseYear: 2025,
      releaseDateFormatted: 'Mar 20, 2025',
      genres: ['Action', 'Stealth', 'RPG'],
      synopsis: 'Live the intertwined stories of Naoe, an adept shinobi Assassin from Iga Province, and Yasuke, the powerful African samurai of historical legend, set against the turbulent backdrop of Sengoku-era Japan.',
      communityRating: 8.5,
      creator: 'Ubisoft',
      runtimeMinutes: 2400,
    ),
    const MediaItem(
      id: 'game_elden_ring',
      title: 'Elden Ring',
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc82y9.webp',
      releaseYear: 2022,
      releaseDateFormatted: 'Feb 25, 2022',
      genres: ['Action', 'RPG', 'Dark Fantasy'],
      synopsis: 'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
      communityRating: 9.6,
      creator: 'FromSoftware',
      steamAppId: 1245620,
      runtimeMinutes: 3600,
    ),
    const MediaItem(
      id: 'game_witcher3',
      title: 'The Witcher 3: Wild Hunt',
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc66l5.webp',
      releaseYear: 2015,
      releaseDateFormatted: 'May 19, 2015',
      genres: ['RPG', 'Open World', 'Fantasy'],
      synopsis: 'You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will.',
      communityRating: 9.5,
      creator: 'CD PROJEKT RED',
      steamAppId: 292030,
      runtimeMinutes: 4200,
    ),
    const MediaItem(
      id: 'game_tlou1',
      title: 'The Last of Us Part I',
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5x78.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc82ym.webp',
      releaseYear: 2022,
      releaseDateFormatted: 'Sep 2, 2022',
      genres: ['Action', 'Adventure', 'Cinematic'],
      synopsis: 'In a ravaged civilization, where infected and hardened survivors run rampant, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone.',
      communityRating: 9.3,
      creator: 'Naughty Dog',
      steamAppId: 1888930,
      runtimeMinutes: 960,
    ),
    const MediaItem(
      id: 'game_silksong',
      title: 'Hollow Knight: Silksong',
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2kch.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc73j1.webp',
      releaseYear: 2025,
      releaseDateFormatted: 'TBA 2025',
      genres: ['Metroidvania', 'Platformer', 'Action'],
      synopsis: 'Discover a vast, haunted kingdom in Hollow Knight: Silksong! Explore, fight and survive as Hornet, princess-protector of Hallownest.',
      communityRating: 9.7,
      creator: 'Team Cherry',
      steamAppId: 1030300,
      runtimeMinutes: 1800,
    ),
    const MediaItem(
      id: 'game_pathologic3',
      title: 'Pathologic 3',
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8vvg.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/scny4b.webp',
      releaseYear: 2025,
      releaseDateFormatted: '2025',
      genres: ['Survival', 'Psychological Horror', 'Adventure'],
      synopsis: 'Assume the role of the Bachelor, an educated town doctor battling an apocalyptic outbreak in a bizarre town in the steppe.',
      communityRating: 8.8,
      creator: 'Ice-Pick Lodge',
      runtimeMinutes: 1200,
    ),
    const MediaItem(
      id: 'game_re_requiem',
      title: 'Resident Evil Requiem',
      mediaType: MediaType.game,
      posterUrl: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.webp',
      backdropUrl: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc82y9.webp',
      releaseYear: 2026,
      releaseDateFormatted: 'Oct 2026',
      genres: ['Survival Horror', 'Action'],
      synopsis: 'A terrifying return to high-stakes biological horrors and dark secrets.',
      communityRating: 8.8,
      creator: 'Capcom',
      runtimeMinutes: 900,
    ),
  ];

  static final List<MediaItem> sampleCinema = [
    const MediaItem(
      id: 'movie_dune2',
      title: 'Dune: Part Two',
      mediaType: MediaType.movie,
      posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5200bm.jpg',
      releaseYear: 2024,
      releaseDateFormatted: 'Mar 1, 2024',
      genres: ['Sci-Fi', 'Adventure', 'Drama'],
      synopsis: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
      communityRating: 9.0,
      creator: 'Denis Villeneuve',
      runtimeMinutes: 166,
    ),
    const MediaItem(
      id: 'tv_severance',
      title: 'Severance',
      mediaType: MediaType.tvShow,
      posterUrl: 'https://image.tmdb.org/t/p/w500/jtA82x4kL3sMtz7dFkP8eT1o55p.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/bKxiLRPVWe2nZUCyY6i2qR17Z.jpg',
      releaseYear: 2022,
      releaseDateFormatted: 'Feb 18, 2022',
      genres: ['Sci-Fi', 'Mystery', 'Thriller'],
      synopsis: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.',
      communityRating: 8.9,
      creator: 'Dan Erickson (Apple TV+)',
      runtimeMinutes: 55,
    ),
    const MediaItem(
      id: 'tv_arcane',
      title: 'Arcane',
      mediaType: MediaType.tvShow,
      posterUrl: 'https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn397rFriYe9l.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
      releaseYear: 2021,
      releaseDateFormatted: 'Nov 6, 2021',
      genres: ['Animation', 'Sci-Fi', 'Action'],
      synopsis: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.',
      communityRating: 9.4,
      creator: 'Fortiche / Riot Games (Netflix)',
      runtimeMinutes: 42,
    ),
    const MediaItem(
      id: 'movie_oppenheimer',
      title: 'Oppenheimer',
      mediaType: MediaType.movie,
      posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
      releaseYear: 2023,
      releaseDateFormatted: 'Jul 21, 2023',
      genres: ['Drama', 'History', 'Biography'],
      synopsis: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.',
      communityRating: 8.9,
      creator: 'Christopher Nolan',
      runtimeMinutes: 180,
    ),
    const MediaItem(
      id: 'tv_shogun',
      title: 'Shōgun',
      mediaType: MediaType.tvShow,
      posterUrl: 'https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSxhOg1WNzG1AgYT.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/5zmiBoMzeWKVc6x1RJ77i8xQv0B.jpg',
      releaseYear: 2024,
      releaseDateFormatted: 'Feb 27, 2024',
      genres: ['Drama', 'History', 'War'],
      synopsis: 'When a mysterious European ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power in feudal Japan.',
      communityRating: 9.2,
      creator: 'Rachel Kondo & Justin Marks (FX)',
      runtimeMinutes: 60,
    ),
    const MediaItem(
      id: 'movie_spiderverse',
      title: 'Spider-Man: Across the Spider-Verse',
      mediaType: MediaType.movie,
      posterUrl: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
      releaseYear: 2023,
      releaseDateFormatted: 'Jun 2, 2023',
      genres: ['Animation', 'Action', 'Adventure'],
      synopsis: 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse.',
      communityRating: 9.1,
      creator: 'Joaquim Dos Santos, Kemp Powers',
      runtimeMinutes: 140,
    ),
  ];

  static List<LibraryEntry> getInitialLibrary() {
    return [
      LibraryEntry(
        id: 'entry_zelda',
        mediaId: 'game_zelda_la',
        mediaItem: sampleGames[0],
        status: LibraryStatus.playing,
        platform: 'Nintendo Switch',
        format: 'Physical',
        progressPercent: 66.0,
        timeSpentMinutes: 808, // 13h 28m
        userRating: 8.5,
        lastActivity: DateTime.now().subtract(const Duration(minutes: 57)),
        notes: 'Exploring Koholint Island. Dungeons have fantastic puzzle design!',
      ),
      LibraryEntry(
        id: 'entry_silent_hill',
        mediaId: 'game_silent_hill_f',
        mediaItem: sampleGames[1],
        status: LibraryStatus.playing,
        platform: 'PC - Steam',
        format: 'Digital',
        progressPercent: 40.0,
        timeSpentMinutes: 554, // 9h 14m
        userRating: 9.0,
        lastActivity: DateTime.now().subtract(const Duration(hours: 1)),
        notes: 'Atmosphere in 1960s Japan is incredible and genuinely creepy.',
      ),
      LibraryEntry(
        id: 'entry_ac_shadows',
        mediaId: 'game_ac_shadows',
        mediaItem: sampleGames[3],
        status: LibraryStatus.completed,
        platform: 'PlayStation 5',
        format: 'Physical',
        progressPercent: 100.0,
        timeSpentMinutes: 2450,
        userRating: 9.0,
        lastActivity: DateTime.now().subtract(const Duration(days: 2)),
        notes: 'Finished the main campaign. Yasuke combat felt heavy and rewarding.',
      ),
      LibraryEntry(
        id: 'entry_elden_ring',
        mediaId: 'game_elden_ring',
        mediaItem: sampleGames[4],
        status: LibraryStatus.completed,
        platform: 'PC - Steam',
        format: 'Digital',
        progressPercent: 100.0,
        timeSpentMinutes: 7200,
        userRating: 10.0,
        lastActivity: DateTime.now().subtract(const Duration(days: 14)),
      ),
      LibraryEntry(
        id: 'entry_witcher3',
        mediaId: 'game_witcher3',
        mediaItem: sampleGames[5],
        status: LibraryStatus.completed,
        platform: 'PC - Steam',
        format: 'Digital',
        progressPercent: 100.0,
        timeSpentMinutes: 5400,
        userRating: 9.5,
        lastActivity: DateTime.now().subtract(const Duration(days: 20)),
      ),
      LibraryEntry(
        id: 'entry_tlou1',
        mediaId: 'game_tlou1',
        mediaItem: sampleGames[6],
        status: LibraryStatus.completed,
        platform: 'PlayStation 5',
        format: 'Physical',
        progressPercent: 100.0,
        timeSpentMinutes: 1020,
        userRating: 9.5,
        lastActivity: DateTime.now().subtract(const Duration(days: 30)),
      ),
      LibraryEntry(
        id: 'entry_silksong',
        mediaId: 'game_silksong',
        mediaItem: sampleGames[7],
        status: LibraryStatus.backlog,
        platform: 'PC - Steam',
        format: 'Digital',
        progressPercent: 0.0,
        timeSpentMinutes: 0,
      ),
      LibraryEntry(
        id: 'entry_fable',
        mediaId: 'game_fable',
        mediaItem: sampleGames[2],
        status: LibraryStatus.backlog,
        platform: 'Xbox Series X',
        format: 'Subscription (Game Pass)',
        progressPercent: 0.0,
        timeSpentMinutes: 0,
      ),
      LibraryEntry(
        id: 'entry_pathologic3',
        mediaId: 'game_pathologic3',
        mediaItem: sampleGames[8],
        status: LibraryStatus.completed,
        platform: 'PC - Steam',
        format: 'Digital',
        progressPercent: 100.0,
        timeSpentMinutes: 429,
        userRating: 8.5,
        lastActivity: DateTime.now().subtract(const Duration(days: 3)),
      ),
      // Cinema Entries
      LibraryEntry(
        id: 'entry_dune2',
        mediaId: 'movie_dune2',
        mediaItem: sampleCinema[0],
        status: LibraryStatus.completed,
        platform: '4K UHD Blu-ray',
        format: 'Physical',
        progressPercent: 100.0,
        timeSpentMinutes: 166,
        userRating: 10.0,
        lastActivity: DateTime.now().subtract(const Duration(days: 5)),
        notes: 'Spectacular sound design and cinematography. Masterpiece in IMAX.',
      ),
      LibraryEntry(
        id: 'entry_severance',
        mediaId: 'tv_severance',
        mediaItem: sampleCinema[1],
        status: LibraryStatus.playing,
        platform: 'Apple TV+',
        format: 'Subscription',
        progressPercent: 75.0,
        timeSpentMinutes: 440,
        userRating: 9.5,
        lastActivity: DateTime.now().subtract(const Duration(hours: 4)),
        notes: 'Season 1 finale cliffhanger is wild. Watching season 2 now.',
      ),
      LibraryEntry(
        id: 'entry_shogun',
        mediaId: 'tv_shogun',
        mediaItem: sampleCinema[4],
        status: LibraryStatus.completed,
        platform: 'Disney+ / Hulu',
        format: 'Subscription',
        progressPercent: 100.0,
        timeSpentMinutes: 600,
        userRating: 9.5,
        lastActivity: DateTime.now().subtract(const Duration(days: 12)),
      ),
    ];
  }

  static List<PlaySession> getInitialSessions() {
    final now = DateTime.now();
    return [
      PlaySession(
        id: 'sess_1',
        mediaId: 'game_silent_hill_f',
        mediaTitle: 'Silent Hill f',
        mediaPoster: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5p1d.webp',
        mediaType: MediaType.game,
        date: now.subtract(const Duration(hours: 1)),
        durationMinutes: 306, // 5 hr, 6 min
        platform: 'PC - Steam',
        notes: 'Explored the flooded village. Puzzles are getting challenging.',
      ),
      PlaySession(
        id: 'sess_2',
        mediaId: 'game_zelda_la',
        mediaTitle: "The Legend of Zelda: Link's Awakening",
        mediaPoster: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7f.webp',
        mediaType: MediaType.game,
        date: now.subtract(const Duration(hours: 3)),
        durationMinutes: 243, // 4 hr, 3 min
        platform: 'Nintendo Switch',
        notes: 'Completed the Key Cavern dungeon.',
      ),
      PlaySession(
        id: 'sess_3',
        mediaId: 'game_ac_shadows',
        mediaTitle: "Assassin's Creed Shadows",
        mediaPoster: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co87o0.webp',
        mediaType: MediaType.game,
        date: now.subtract(const Duration(days: 1, hours: 2)),
        durationMinutes: 180,
        platform: 'PlayStation 5',
        isCompletion: true,
        rating: 9.0,
        notes: '1 playthrough completed. Outstanding historical recreation.',
      ),
      PlaySession(
        id: 'sess_4',
        mediaId: 'game_pathologic3',
        mediaTitle: 'Pathologic 3',
        mediaPoster: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8vvg.webp',
        mediaType: MediaType.game,
        date: now.subtract(const Duration(days: 2, hours: 5)),
        durationMinutes: 429, // 7 hr, 9 min
        platform: 'PC - Steam',
        isCompletion: true,
        rating: 8.5,
      ),
      PlaySession(
        id: 'sess_5',
        mediaId: 'tv_severance',
        mediaTitle: 'Severance',
        mediaPoster: 'https://image.tmdb.org/t/p/w500/jtA82x4kL3sMtz7dFkP8eT1o55p.jpg',
        mediaType: MediaType.tvShow,
        date: now.subtract(const Duration(days: 3)),
        durationMinutes: 110, // 2 episodes
        platform: 'Apple TV+',
        rating: 9.5,
        notes: 'Watched episodes 7 & 8. Absolutely tense.',
      ),
      PlaySession(
        id: 'sess_6',
        mediaId: 'movie_dune2',
        mediaTitle: 'Dune: Part Two',
        mediaPoster: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        mediaType: MediaType.movie,
        date: now.subtract(const Duration(days: 5)),
        durationMinutes: 166,
        platform: '4K UHD Blu-ray',
        isCompletion: true,
        rating: 10.0,
        notes: 'Rewatch with Atmos audio. Mind-blowing immersion.',
      ),
    ];
  }
}
